### ISSUE TITLE
Support for 4k Screen

### ISSUE THREAD

**Issue by ghost** [Nihhaar/Hackintosh-Dell-7567#1]
Hi Can you help me get my Dell 7567 working with 4k Screen.
I tried making a usb as per your instructions. It fails to boot after initial verbose output.
I think it has to do something with ig-platform-id.

I am not sure where do i add this invalid ig-platform-id so that i can get to the installer.

**Comment by Nihhaar** [comment]
Sorry for replying late, my instructions are only for 1080p version. 
For 4k, to boot the usb, you probably need this kext: https://github.com/PMheart/CoreDisplayFixup (along with Lilu.kext) .  And also DVMT may be inadequate. 
If you want to patch these at later time, you have to use a bogus fakeID (0x12345678). This can be set in config.plist file (set ig-platform-id to 0x12345678).

Closing this because I don't have a 4k laptop to support you further.
