### ISSUE TITLE
cannot boot to macOS Mojave with Clover post installation

### ISSUE THREAD

**Issue by AnharmA** [Nihhaar/Hackintosh-Dell-7567#12]
I did everything mentioned in guide, but I can’t boot to macOS Mojave using post installation Clover, it always went 50% in loading screen then it restarted itself. When I’m using Clover from USB, it booted normally

**Comment by Nihhaar** [comment]
Can you attach the post-install files you were using?

Since the USB files are working, the most obvious approach is to update/add from USB files one-by-one:
* Update config.plist & add VoodooI2C kexts & DSDT, SSDT patches (since some patches in config.plist has dependencies on VoodooI2C and SSDTs)
* Update remaining kexts one-by-one
See at what point you are getting a panic and proceed to find the reason causing it.

**Comment by AnharmA** [comment]
I removed all the kext and still nothing.
Should I download your previous release to copy /Library/LaunchDaemons and /usr/bin folder? Im using Mojave

**Comment by Nihhaar** [comment]
No need.
You see since the USB files are working but post-install are not, some kext or 'a patch in config.plist' is causing the panic.
* See if you can boot via recovery?
* Did you follow all the steps exactly? (rethink)
* Is this a fresh install of mojave or you updating from previous high sierra? May be you used my previous files and you forgot to remove them?
* If not all above, diff between USB and post-install files and incremently update your configuration to find out what is causing the panic. (Nothing I can do here bcoz it is working perfectly fine for me)

**Comment by AnharmA** [comment]
This is fresh and full installation of hackintosh.
I followed ur guide without missing anything, the only think that confuses me are the kext file, what to put on clover and the one in L/E, is it going to ~/Library/Extension or System/Library/Extension?

**Comment by Nihhaar** [comment]
Clover:Other -> Clover/Other
:L:E -> /Library/Extensions (no telda)

**Comment by Nihhaar** [comment]
Also, your SATA operation must be set to AHCI in BIOS.

**Comment by AnharmA** [comment]
Now with post Clover, Apple logo and loading bar shows, but it restarted immediately. With USB still boot normally. Should I reinstall my hackintosh?

**Comment by Nihhaar** [comment]
No need to reinstall. Try booting it verbose. It is definitely kernel panic caused by some kext. It's working fine for me, so not sure why. What is your laptop specs? and bios version?

**Comment by AnharmA** [comment]
Same specs as your laptop, but with 1.8.1 bios. Also triple boot with Windows 10 and Ubuntu 18.04

Can I provide the video or is Clover generating log for that kernel panic?

**Comment by Nihhaar** [comment]
I'm not sure I can help as I am not an expert. Post here for help(ask rehabman):
https://www.tonymacx86.com/threads/guide-dell-inspiron-15-7567-and-similar-near-full-functionality.234988/

**Comment by AnharmA** [comment]
Did I just need to install the Kext from "Clover/Other Kext" folder? How about from "/L/E Kext"? You didn't mention to install it

**Comment by Nihhaar** [comment]
kexts from "Clover/Other Kext" folder goes to your `EFI/Clover/Other` on your system. kexts from "/L/E Kext" go to `/Library/Extensions` folder on your system.

Installing means just copying. Don't use any kext installer/utility

**Comment by Nihhaar** [comment]
I'm really sorry. I realized now only that the README is wrong. I'll update now. Sorry for the inconvenience.

**Comment by hhoangna** [comment]
@AnharmA I had a same ur issue. Did you resolve?

**Comment by hhoangna** [comment]
> kexts from "Clover/Other Kext" folder goes to your `EFI/Clover/Other` on your system. kexts from "/L/E Kext" go to `/Library/Extensions` folder on your system.
> 
> Installing means just copying. Don't use any kext installer/utility

i used kext utilities to install kexts in Clover/Other. Is it the cause of the error?

**Comment by Nihhaar** [comment]
I think kext utilities can't install kexts to EFI partition. Just manually copy.

**Comment by hhoangna** [comment]
Yup! I manually copied. Then, i used Kext Utility application like this
![screen shot 2018-10-16 at 1 12 56 pm](https://user-images.githubusercontent.com/26923574/46995996-395aca00-d145-11e8-91df-638b2caf410d.png)

Is it the cause of the error?

**Comment by AnharmA** [comment]
I think kext used from post Clover causing the boot problem

**Comment by fangcha** [comment]
Hi, I didn't want to create new issue since I think I have the same problem.

I followed this guide by using the new release 2.0.0 (Mojave Support) and it will not boot post installation UNLESS DSDT.aml is removed from EFI/CLOVER/ACPI/patched then it will boot successfully.

but the problem is the system reboots randomly without any obvious reason (sometime 2-3 hours after first successful boot, sometimes 30 mins) THEN it will NOT boot again unless I power off the device completely and turning it on again.

Any Idea or help would be much appreciated.
Thanks very much for writing this guide in the first place

**Comment by Nihhaar** [comment]
Removed DSDT aml in the latest release, so the latest files should work fine
